[package]
name = "flume"
version = "0.10.1"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"
description = "A blazingly fast multi-producer channel"
repository = "https://github.com/zesterer/flume"
keywords = ["mpsc", "fifo", "channel", "thread", "fast"]
categories = ["concurrency", "data-structures"]
license = "Apache-2.0/MIT"
readme = "README.md"
exclude = [
	"/.github",
	"/misc",
]

[features]
select = []
async = ["futures-sink", "futures-core", "pin-project"]
eventual-fairness = ["async", "nanorand"]
default = ["async", "select", "eventual-fairness"]
sgx = ["sgx_tstd"]

[dependencies]
spinning_top = "0.2"
futures-sink = { version = "0.3.5", default_features = false, optional = true }
futures-core = { version = "0.3.5", default_features = false, optional = true }
nanorand = { version = "0.5", features = ["getrandom"], optional = true }
pin-project = { version = "1", optional = true }
sgx_tstd = { path = "../incubator-teaclave-sgx-sdk/sgx_tstd", features = ["backtrace", "thread", "untrusted_time"], optional = true }

[dev-dependencies]
#flume-test = { path = "../flume-test" }
crossbeam-channel = "0.4"
crossbeam-utils = "0.7"
criterion = "0.3.1"
rand = "0.7"
async-std = { version = "1.5", features = ["attributes", "unstable"] }
futures = { version = "^0.3", features = ["std"] }
waker-fn = "1.1.0"

[[bench]]
name = "basic"
harness = false
